### ISSUE TITLE
Add Additional Functions

### ISSUE THREAD

**Issue by DrLongGhost** [spam-n-eggs/laravel-mysqlite#22]
Please add support for the following functions:

* date_format
* LPAD
* mod
* minute
* format
* CONVERT_TZ
* TIMEDIFF
* UNIX_TIMESTAMP
* weekday
* inet_ntoa

Add support for the following modifiers:
* INTERVAL

**Comment by spam-n-eggs** [comment]
@DrLongGhost This is really helpful.  I'll get started on them.

**Comment by spam-n-eggs** [comment]
✅ DATE_FORMAT
✅ LPAD

**Comment by spam-n-eggs** [comment]
✅ MOD
✅ MINUTE
✅ FORMAT
👍UNIX_TIMESTAMP - Is already implemented.

**Comment by spam-n-eggs** [comment]
✅ CONVERT_TZ
✅ TIMEDIFF
✅ WEEKDAY
✅ INET_NTOA

**Comment by spam-n-eggs** [comment]
✅ DATE_ADD with INTERVAL
